version: 2
jobs:
  build:
    working_directory: ~/app
    machine: true
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
            make build ENV=local ENV_FILE=local
      - run:
          name: Run tests
          command: |
            make test ENV=local ENV_FILE=local
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              make build AWS_VAR_PREFIX=AWS_PRODUCTION ENV=production ENV_FILE=production
              make deploy AWS_VAR_PREFIX=AWS_PRODUCTION ENV=production S3_CP_ARGS="--exclude '*.map'" ENV_FILE=production
            fi
